# Use the official PostgreSQL 16.2 image as the base
FROM postgres:16.2

# Optional: Set the default environment variables
ENV POSTGRES_DB=default_db
ENV POSTGRES_USER=default_user
ENV POSTGRES_PASSWORD=default_password  

# The default command will run PostgreSQL upon container start-up
CMD ["postgres"]