version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    restart: always
    deploy:
      replicas: 2
    networks:
      - shared_swarm_network
      
networks:
  shared_swarm_network:
    external: true