version: '3.8'

services:
  nginx:
    image: yasilo8240/jobplus-nginx:latest
    ports:
      - '80:80'  # Expose Nginx on port 80
    restart: always
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
      update_config:
        order: start-first
    networks:
      - shared_swarm_network

  visualizer:
    image: dockersamples/visualizer
    # Removed ports: '8500:8080' to not expose directly
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]

  jobplus-postgres:
    image: yasilo8240/jobplus-postgres:latest
    environment:
      POSTGRES_USER: jobplus_user
      POSTGRES_PASSWORD: D3vB*tWsmP3@6#A!
      POSTGRES_DB: jobplus_prod
    networks:
      - shared_swarm_network
    volumes:
      - /mnt/shared_storage/postgres-data:/var/lib/postgresql/data
    deploy:
      replicas: 4
      placement:
        constraints: [node.role == worker]

  # etcd container acts as a distributed key-value store for cluster configuration and state management.
  etcd:
    image: yasilo8240/jobplus-etcd:latest
    ports:
      - '2379:2379' # For client communication
      - '2380:2380' # For other etcd nodes communication
    volumes:
      - etcd_data:/etcd-data
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]

volumes:
  etcd_data:
  
networks:
  shared_swarm_network:
    external: true