version: '3.8'

services:
  nginx:
    image: yasilo8240/jobplus-nginx:latest
    ports:
      - '80:80' # Expose Nginx on port 80
    restart: always
    deploy:
      replicas: 3
      placement:
        constraints: [node.role == worker]
      update_config:
        order: start-first
    networks:
      - shared_swarm_network

  visualizer:
    image: dockersamples/visualizer
    # Removed ports: '8500:8080' to not expose directly
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]

  consul:
    image: yasilo8240/jobplus-consul:latest
    command: ["consul", "agent", "-server", "-bootstrap-expect=1", "-config-dir=/consul/config"]
    volumes:
      - '/mnt/shared_storage/consul-data:/consul/data'
    ports:
      - '8500:8500' # Expose the Consul UI and API port
      - '8600:8600/udp' # DNS interface
    environment:
      CONSUL_BIND_INTERFACE: 'eth0'
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == worker]

networks:
  shared_swarm_network:
    external: true
