version: '3.8'

secrets:
  pgsql:
    file: ./services/stolon/secrets/pgsql
  pgsql_repl:
    file: ./services/stolon/secrets/pgsql_repl

services:
  # consul:
  #   image: yasilo8240/jobplus-consul:latest
  #   volumes:
  #     # - '/mnt/shared_storage/consul-data:/consul-data'
  #     - console_data:/consul/data
  #   ports:
  #     - '8500:8500'  # Expose the Consul UI and API port
  #     - "8400:8400"
  #     - "8301-8302:8301-8302"
  #     - "8301-8302:8301-8302/udp"
  #     - "8600:8600"
  #     - "8600:8600/udp"
  #   networks:
  #     - shared_swarm_network
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager] # change to worker later if needed
  #     restart_policy:
  #       condition: on-failure
  #   environment:
  #     CONSUL_BIND_INTERFACE: 'eth0'
  #     CONSUL_CLIENT_INTERFACE: 'eth0'
  #   command: "agent -server -ui -bootstrap -client=0.0.0.0 -bind={{ GetInterfaceIP 'eth0' }} -data-dir=/consul/data"

  # etcd container acts as a distributed key-value store for cluster configuration and state management.
  etcd:
    image: yasilo8240/jobplus-etcd:latest
    ports:
      - '2379:2379' # For client communication
      - '2380:2380' # For other etcd nodes communication
    volumes:
      # - '/mnt/shared_storage/etcd-data:/etcd-data'
      - etcd_data:/etcd-data
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]
  # Managing Stolon clusters, providing operational control.
  stolon-ctl:
    image: yasilo8240/jobplus-stolon:latest
    environment:
      - ROLE=ctl
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]

  # Runs Stolon Keeper managing PostgreSQL data persistence and replication.
  stolon-keeper:
    image: yasilo8240/jobplus-stolon:latest
    depends_on:
      - stolon-ctl
      - etcd
    environment:
      - ROLE=keeper
      - STKEEPER_UID=postgres_{{.Task.ID}}
      - PG_REPL_USERNAME=repluser
      # - PG_REPL_PASSWORD=replpass
      - PG_REPL_PASSWORD_FILE=/run/secrets/pgsql_repl
      - PG_SU_USERNAME=postgres
      # - PG_SU_PASSWORD=postgres
      - PG_SU_PASSWORD_FILE=/run/secrets/pgsql
    secrets:
      - pgsql
      - pgsql_repl
    volumes:
      - stolon_data:/stolon/data
      - pg_data:/var/lib/postgresql/data
      - pg_log:/var/log/postgresql
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]

  # Deploys Stolon Sentinel for monitoring and orchestrating cluster failovers.
  stolon-sentinel:
    image: yasilo8240/jobplus-stolon:latest
    environment:
      - ROLE=sentinel
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - stolon-keeper
      - etcd

volumes:
  stolon_data:
  console_data:
  pg_data:
  pg_log:
  etcd_data:

networks:
  shared_swarm_network:
    external: true

