version: '3.8'

services:
  # etcd container acts as a distributed key-value store for cluster configuration and state management.
  etcd:
    image: yasilo8240/jobplus-etcd:latest
    ports:
      - '2379:2379' # For client communication
      - '2380:2380' # For other etcd nodes communication
    volumes:
      # - '/mnt/shared_storage/etcd-data:/etcd-data'
      - etcd_data:/etcd-data
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]

  # Managing Stolon clusters, providing operational control.
  stolon-ctl:
    image: yasilo8240/jobplus-stolon:latest
    environment:
      - ROLE=ctl
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]

  # # Runs Stolon Keeper managing PostgreSQL data persistence and replication.
  stolon-keeper:
    image: yasilo8240/jobplus-stolon:latest
    environment:
      - ROLE=keeper
      - STKEEPER_UID=postgres_{{.Task.ID}}
      - PG_REPL_USERNAME=repluser
      - PG_REPL_PASSWORD=repl_password
      - PG_SU_USERNAME=postgres
      - PG_SU_PASSWORD=su_password
    volumes:
      - stolon_data:/stolon/data
      - pg_data:/var/lib/postgresql/data
      - pg_log:/var/log/postgresql
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]

  # stolon-keeper:
  #   image: sorintlab/stolon:master-pg10
  #   hostname: keeper1
  #   environment:
  #     - PGDATA=/var/lib/postgresql/data
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  #   command: gosu stolon stolon-keeper --pg-listen-address keeper1 --pg-repl-username replication --uid keeper1 --pg-su-username postgres --pg-su-password password1 --pg-repl-password password2 --data-dir /var/lib/postgresql/data --cluster-name stolon-cluster --store-backend=etcdv3 --store-endpoints http://etcd:2379
  #   networks:
  #     - shared_swarm_network
  #   deploy:
  #     placement:
  #       constraints: [node.role == manager]

  # Deploys Stolon Sentinel for monitoring and orchestrating cluster failovers.
  stolon-sentinel:
    image: yasilo8240/jobplus-stolon:latest
    environment:
      - ROLE=sentinel
    networks:
      - shared_swarm_network
    deploy:
      placement:
        constraints: [node.role == manager]
    depends_on:
      - stolon-keeper
      - etcd

volumes:
  stolon_data:
  console_data:
  pg_data:
  pg_log:
  etcd_data:

networks:
  shared_swarm_network:
    external: true

