scope: postgres
namespace: /db/
name: postgresql0

restapi:
  listen: 0.0.0.0:8008
  connect_address: localhost:8008

etcd:
  host: etcd:2379

bootstrap:
  initdb:
    - encoding: UTF8
    - data-checksums
  pg_hba:
    - host replication replicator 127.0.0.1/32 md5
    - host all all 0.0.0.0/0 md5
  postgresql:
    parameters:
      listen_addresses: '0.0.0.0'
      port: 5432
      max_connections: 100
      max_locks_per_transaction: 64
      max_prepared_transactions: 0
      max_replication_slots: 10
      max_wal_senders: 10
      max_worker_processes: 8
      wal_level: replica
      wal_keep_segments: 8
      hot_standby: on
      track_commit_timestamp: off

# bootstrap:
#   dcs:
#     ttl: 30
#     loop_wait: 10
#     retry_timeout: 10
#     maximum_lag_on_failover: 1048576
#     postgresql:
#       use_pg_rewind: true
#       use_slots: true
#       parameters:
#         max_connections: 100
#   initdb:
#     - encoding: UTF8
#     - data-checksums
#   pg_hba:
#     - host replication replicator 127.0.0.1/32 md5
#     - host all all 0.0.0.0/0 md5

postgresql:
  listen: 0.0.0.0:5432
  connect_address: localhost:5432
  data_dir: /var/lib/postgresql/data
  bin_dir: /usr/lib/postgresql/16/bin
  pgpass: /tmp/pgpass
  authentication:
    replication:
      username: replicator
      password: rep-pass
    superuser:
      username: postgres
      password: secretpassword
  parameters:
    unix_socket_directories: '.'

