---
- name: Setup Common Tasks & Gluster Install
  hosts: servers
  become: yes
  roles:
    - common_tasks
    - gluster_install

- name: Gluster Shared Volume
  hosts: swarm_managers[0]
  become: yes
  roles:
    - gluster_shared_volume
  tags:
    - swarm_shared_volume

- name: Mount GlusterFS Volume on all Nodes
  hosts: servers
  become: yes
  roles:
    - gluster_mount_volume

- name: Swarm Initialize
  hosts: swarm_managers[0]
  become: yes
  roles:
    - swarm_initialize
  tags:
    - swarm_initialize

- name: Join Swarm as workers
  hosts: swarm_workers
  become: yes 
  roles: 
    - join_swarm 
  tags:
    - add_workers_to_swarm