# Ansible processes these plays in the order they are defined, maintaining a clear and organized flow of configuration tasks across the different host groups.
# Parallelism is managed by Ansible's 'forks' configuration, allowing multiple hosts to be configured in parallel up to the specified limit.

---
- hosts: servers
  become: yes
  roles:
    # These will be install on all nodes
    - common_tasks
    - gluster_install

- hosts: swarm_managers
  become: yes
  tasks:
    # through manager we create shared directory
    # on all nodes, but this can be achieved just
    # from one node. e.g manager
    - name: Conditionally execute on the first manager only
      include_role:
        name: gluster_shared_volume
      when: inventory_hostname == groups['swarm_managers'][0]

- hosts: servers
  become: yes
  roles:
    # We need this to run after swarm manager has created
    # gluster_shared_volume
    - gluster_mount_volume