---
- name: Common Tasks
  hosts: servers
  become: yes
  roles:
    - common_tasks

- name: Deploy User Setup 
  hosts: servers
  become: yes
  roles:
    - deployuser_setup
    
- name: Gluster Install
  hosts: servers
  become: yes
  roles:
    - gluster_install

- name: Probe nodes to form gluster pool
  hosts: swarm_managers[0]
  become: yes 
  roles:
    - gluster_probe
  tags:
    - gluster_probe

- name: Gluster Shared Volume
  hosts: swarm_managers[0]
  become: yes
  roles:
    - gluster_shared_volume
  tags:
    - swarm_shared_volume

- name: Mount GlusterFS Volume on all Nodes
  hosts: servers
  become: yes
  roles:
    - gluster_mount_volume

- name: Etcd Setup
  hosts: servers
  become: yes
  roles:
    - etcd_setup
  tags:
    - etcd_setup

- name: Swarm Initialize
  hosts: swarm_managers[0]
  become: yes
  roles:
    - swarm_initialize
  tags:
    - swarm_initialize

- name: Join Swarm as workers
  hosts: swarm_workers
  become: yes 
  roles: 
    - join_swarm 
  tags:
    - add_workers_to_swarm

- name: Join Swarm as managers
  hosts: swarm_managers
  become: yes 
  roles: 
    - join_swarm 
  tags:
    - add_managers_to_swarm