swarm_manager_public_ip: "134.209.19.136"
swarm_worker_join_token: "SWMTKN-1-28det9r4qo40562ntgisaubepdpvv51nwu3goshc32nj2bz4k1-46qrdpvm5bggb8jl4ywb3lsio"
swarm_manager_join_token: "SWMTKN-1-28det9r4qo40562ntgisaubepdpvv51nwu3goshc32nj2bz4k1-5v3dvpdtdd2pxvibtcxsi5yg8"
