---
- name: Update apt and install dependencies
  apt:
    name: '{{ packages }}'
    update_cache: yes
  vars:
    packages:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - git

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Get Ubuntu codename
  command: lsb_release -cs
  register: ubuntu_codename

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable'
    state: present

- name: Install Docker CE
  apt:
    name: docker-ce
    update_cache: yes

- name: Enable Docker service
  systemd:
    name: docker
    enabled: yes

- name: Install Docker Compose
  remote_user: ubuntu
  get_url:
    url: 'https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-linux-x86_64'
    dest: /usr/local/bin/docker-compose
    mode: '0755'

# DigitalOcean Monitoring Agent
- name: Install DigitalOcean Monitoring Agent
  shell: 'curl -sSL https://repos.insights.digitalocean.com/install.sh | sudo bash'

# Open Firewall Ports for HTTP and HTTPS
- name: Allow HTTP traffic
  community.general.ufw:
    rule: allow
    port: '80'
    proto: tcp
  tags:
    - firewall_allow

- name: Allow HTTPS traffic
  community.general.ufw:
    rule: allow
    port: '443'
    proto: tcp

- name: Install Python Docker package via apt
  ansible.builtin.apt:
    name: python3-docker
    state: present
    update_cache: yes
  become: yes
  tags:
    - python_docker

- name: Download etcdctl binary
  get_url:
    url: 'https://github.com/etcd-io/etcd/releases/download/v3.3.25/etcd-v3.3.25-linux-amd64.tar.gz'
    dest: '/tmp/etcd-v3.3.25-linux-amd64.tar.gz'
    mode: '0644'

- name: Extract etcdctl binary
  unarchive:
    src: '/tmp/etcd-v3.3.25-linux-amd64.tar.gz'
    dest: '/tmp'
    remote_src: yes
    creates: '/tmp/etcd-v3.3.25-linux-amd64'

- name: Move etcdctl to /usr/local/bin
  command: mv /tmp/etcd-v3.3.25-linux-amd64/etcdctl /usr/local/bin/etcdctl
  args:
    creates: /usr/local/bin/etcdctl
