name: Build and Push

on:
  push:
    branches:
      - experimental

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Testing
        run: |
          echo "Running next workflow step..."
