name: Build and Push

on:
  workflow_run:
    workflows: ["Deploy Code"]
    branches: [experimental]
    types:
      - completed

      
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Testing
        run: |
          echo "Running next workflow step..."
