name: Build and Push

on:
  workflow_dispatch:
    inputs:
      changed_services_with_stack:
        description: 'Track which services and stacks were updated'
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Testing
        run: |
          echo "Running next workflow step..."
