name: Stack Deploy

on:
  workflow_dispatch:

jobs:
  stack-deploy:
    runs-on: ubuntu-latest
    env:
      APP_DIR_PATH: /mnt/shared_storage/jobplus-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: experimental

      - name: Deploy Changed Services
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no deployuser@${{ secrets.MANAGER_RESERVED_IP }} "\
          cd $APP_DIR_PATH && \
          docker stack deploy -c docker-compose.yml app_stack"
