# This inventory.ini file was generated by terraform and should be used 
# with ansible  to manage the swarm cluster created by terraform /templates/inventory.tpl

[swarm_managers]
manager1 ansible_host=${manager_ip} ansible_ssh_user=root ansible_ssh_private_key_file=${ssh_private_key}

[swarm_workers]
worker1 ansible_host=${worker_ip} ansible_ssh_user=root ansible_ssh_private_key_file=${ssh_private_key}

[servers:children]
swarm_managers
swarm_workers